language: cpp
sudo: false
dist: bionic

notifications:
  slack: c0demonk3ys:gnjXYwuoMOBnffg9h8YnlLyE

git:
  depth: 5

matrix:
  include:
    - name: "GCC (Debug, ThirdParty)"
      os: linux
      compiler: gcc
      addons:
        apt:
          packages: [ 'g++-7', 'libstdc++-7-dev', 'ninja-build', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "GCC (Debug, System)"
      os: linux
      compiler: gcc
      addons:
        apt:
          packages: [ 'g++-7', 'libstdc++-7-dev', 'ninja-build', 'xorg-dev', 'libglu1-mesa-dev', 'libglfw3-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "GCC (Release, ThirdParty)"
      os: linux
      compiler: gcc
      addons:
        apt:
          packages: [ 'g++-7', 'libstdc++-7-dev', 'ninja-build', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

    - name: "GCC (Release, System)"
      os: linux
      compiler: gcc
      addons:
        apt:
          packages: [ 'g++-7', 'libstdc++-7-dev', 'ninja-build', 'xorg-dev', 'libglu1-mesa-dev', 'libglfw3-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

    - name: "Clang (Debug, ThirdParty)"
      os: linux
      compiler: clang
      addons:
        apt:
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "Clang (Debug, System)"
      os: linux
      compiler: clang
      addons:
        apt:
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'xorg-dev', 'libglu1-mesa-dev', 'libglfw3-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "Clang (Release, ThirdParty)"
      os: linux
      compiler: clang
      addons:
        apt:
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

    - name: "Clang (Release, System)"
      os: linux
      compiler: clang
      addons:
        apt:
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'xorg-dev', 'libglu1-mesa-dev', 'libglfw3-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

before_install:
  - mkdir $HOME/cmake
  - wget -O $HOME/cmake/install.sh https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.sh
  - bash $HOME/cmake/install.sh --prefix=$HOME/cmake --skip-license --exclude-subdir
  - export PATH="$HOME/cmake/bin:$PATH"
  - cmake --version
  - env

script:
  - git describe --tags
  - cd "$TRAVIS_BUILD_DIR/build"
  - cmake -Dstdlib=libstdc++ -DVERBOSE_LOGGING=ON -G "Unix Makefiles" "$TRAVIS_BUILD_DIR"
  - make -l
