language: cpp
sudo: false
dist: xenial

notifications:
  slack: c0demonk3ys:gnjXYwuoMOBnffg9h8YnlLyE

git:
  depth: 5

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'llvm-toolchain-xenial-6.0', 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'llvm-toolchain-xenial-6.0', 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

before_install:
  - env
  - export SRC_DIR="`pwd`"
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-6.0" CC="clang-6.0"; fi

script:
  - $CXX --version
  - cmake --version
  - mkdir "$TRAVIS_BUILD_DIR/build"
  - cd "$TRAVIS_BUILD_DIR/build"
  - pwd
  - cmake -Dstdlib=libstdc++ -G "Unix Makefiles" "$SRC_DIR"
  - make -j
